/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  CalimeroApp,
  Context,
} from '@calimero-network/calimero-client';

// Generated types

export interface ChatInfo {
  total_messages: number;
  max_messages: number;
}

export interface ChatMessage {
  id: number;
  sender: string;
  role: string;
  content: string;
  timestamp_ms: number;
}




export type AbiEvent =
  | { name: "MessageAdded" }
  | { name: "HistoryCleared" }
  | { name: "MaxMessagesUpdated" }
;


/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === "string") {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every(item => typeof item === "number")) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class AbiClient {
  private app: CalimeroApp;
  private context: Context;

  constructor(app: CalimeroApp, context: Context) {
    this.app = app;
    this.context = context;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this.app.execute(this.context, 'init', {});
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * send_message
   */
  public async sendMessage(params: { sender: string; role: string; content: string }): Promise<ChatMessage> {
    const response = await this.app.execute(this.context, 'send_message', params);
    if (response.success) {
      return response.result as ChatMessage;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * messages
   */
  public async messages(params: { offset: number | null; limit: number | null }): Promise<ChatMessage[]> {
    const response = await this.app.execute(this.context, 'messages', params);
    if (response.success) {
      return response.result as ChatMessage[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * clear_history
   */
  public async clearHistory(): Promise<void> {
    const response = await this.app.execute(this.context, 'clear_history', {});
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * set_max_messages
   */
  public async setMaxMessages(params: { max_messages: number }): Promise<void> {
    const response = await this.app.execute(this.context, 'set_max_messages', params);
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * info
   */
  public async info(): Promise<ChatInfo> {
    const response = await this.app.execute(this.context, 'info', {});
    if (response.success) {
      return response.result as ChatInfo;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

}